title: Toko Bunga Lampung
description: Papan Bunga Bandar Lampung Online Murah jual karangan ucapan dan buket mawar segar buka 24 jam.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tokobungalampung.xyz" # the base hostname & protocol for your site, e.g. http://example.com
color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _posts

exclude:
  - .sass-cache

theme: #
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-pwa-plugin
